language: go
go:
- 'tip'

sudo: false
services:
before_install:
  - npm update -g npm
  - npm --version
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
	- sudo apt-get update -qq
	- sudo apt-get install -qq phantomjs
before_script:
script:
  - go test -v
  - go test -v ./handlers
  - npm test
  - npm run-script build.prod
notifications:
  email: tr
after_failure: cat /home/travis/build/gitu/gocash/npm-debug.log
env:
  global:
  # https://github.com/DefinitelyTyped/tsd#tsdrc
  # Token has no scope (read-only access to public information)
  - TSD_GITHUB_TOKEN=9b18c72997769f3867ef2ec470e626d39661795d
