language: go
go:
  - 'tip'
  - '1.5'

sudo: false
services:
before_install:
  - pwd
  - npm update -g npm
  - npm --version
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - go get -t -v ./backend/...
  - npm install
script:
  - go test -v ./backend/...
  - npm test
  - npm run-script build.prod
notifications:
  email: tr
after_failure: cat /home/travis/build/gitu/gocash/npm-debug.log
env:
  global:
  # https://github.com/DefinitelyTyped/tsd#tsdrc
  # Token has no scope (read-only access to public information)
  - TSD_GITHUB_TOKEN=9b18c72997769f3867ef2ec470e626d39661795d

cache:
  directories:
  - node_modules
