language: go
go:
  - 'tip'
  - '1.5'
nodejs:
  - '4.1'
  - '5.3'

addons:
 postgresql: "9.4"

services:
  - postgresql


before_script:
  - psql -c 'create database gocash;' -U postgres

sudo: false
services:
before_install:
  - npm --version
  - node --version
  - npm update -g npm
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm -v
  - node -v
  - go get github.com/tools/godep

install:
  - npm install
  - godep restore
script:
  - goose status
  - goose up && goose down && goose up
  - goose status
  - go test -v .
  - go test -v ./handlers
  - npm test
  - npm run-script build.prod
notifications:
  email: tr
after_failure: cat /home/travis/build/gitu/gocash/npm-debug.log
env:
  global:
  - TSD_GITHUB_TOKEN=9b18c72997769f3867ef2ec470e626d39661795d

cache:
  directories:
  - node_modules
